export const errorMessages = {
  purchaseSuccessful: 'تمت عملية الشراء بنجاح',
  purchaseError: 'خطأ في عملية الشراء',
  noTokens: 'لا توجد نقاط',
  minLength: 'مطلوب حرفين كحد أدنى',
  noConnection: 'لا يوجد اتصال بالإنترنت',
  textCopied: 'تم نسخ النص',
  anErrorOccurred: 'حدث خطأ,حاول مرة اخرى',
  serverError: 'حدث خطأ في الخادم',
  errorPurchasingPackage: 'حدث خطأ أثناء عملية شراء الحزمة',
  errorDuringConnectionRetrying: 'حدث خطأ في الاتصال، جار المحاولة مجدداً',
  showAds: 'شاهد إعلاناً للحصول على نقاط',
  noAdsNow: 'لا يوجد إعلانات في الوقت الحاضر ، يرجى المحاولة لاحقًا و شكرا.',
  choosepackage: ' من فضلك، اختر حزمة الاشتراك قبل الضغط على زر الاستمرار.',
  tryAgain: 'هل ترغب في المحاولة مرة أخرى؟',
  drawAndAddText: 'من فضلك قم بالرسم وإدخال النص قبل الإرسال!',
  dataSent: 'تم إرسال البيانات بنجاح!',
  dataFailed: 'فشل إرسال البيانات!',
  imageSavedToGallery: 'تم حفظ الصورة في المعرض',
  errorWhileSavingImage: 'حدث خطأ أثناء حفظ الصورة في المعرض',
  errorWhileDownloading: 'حدث خطأ أثناء تنزيل الصورة',
};
